### ISSUE TITLE
cannot get `curl http://localhost:3000`

### ISSUE THREAD

**Issue by lduboeuf** [ListnPlay/riot-isomorphic#11]
hi,
after all install instructions, running  `gulp` and trying to get `http://localhost:3000` throw this log output:

tried to update riot.js lib but do the same

```
gulp
[22:19:19] Using gulpfile ~/dev/js/riot/riot-isomorphic/gulpfile.js
[22:19:19] Starting 'html'...
[22:19:19] Finished 'html' after 14 ms
[22:19:19] Starting 'css'...
[22:19:19] Starting 'public-lib'...
[22:19:19] Starting 'js-client'...
[22:19:19] Starting 'js-server'...
[22:19:19] Starting 'js-app'...
[22:19:19] Starting 'env'...
[22:19:19] Finished 'env' after 27 μs
[22:19:19] Finished 'public-lib' after 70 ms
[22:19:19] Finished 'js-client' after 72 ms
[22:19:19] Finished 'css' after 172 ms
[22:19:19] Starting 'public-css'...
[22:19:19] Finished 'public-css' after 15 ms
[22:19:19] Finished 'js-server' after 177 ms
[22:19:19] Finished 'js-app' after 186 ms
[22:19:19] Starting 'browserify'...
[22:19:24] Finished 'browserify' after 5.05 s
[22:19:24] Starting 'public'...
[22:19:24] Finished 'public' after 32 ms
[22:19:24] Starting 'serve'...
livereload[tiny-lr] listening on 35729 ...
Component Factory constructed
Routes class constructed!
running routingTable!
User service::Inserting Hooks
Created default user { username: 'test',
  password: '7110eda4d09e062aa5e4a390b0a572ac0d2c0220',
  id: 0 }
Starting server
Node/Feathers app listening at http://:::3000
Socket util - Server init with URL:  http://localhost:3000
Socket connection is open
Default route!
Store base class constructor
Init FruitStore
Store base class constructor
Init AuthStore
Store base class constructor
Init MainStore
Dispatcher initialized.  3  stores
Init Apple tag
App engine error:  [SyntaxError: Unexpected token (]  Filepath:  /home/lionel/dev/js/riot/riot-isomorphic/build/index.html  Callback:  function (err, str) {
    if (err) return req.next(err);
    self.send(str);
  }
SyntaxError: Unexpected token (
    at Function (native)
    at _create (/home/lionel/dev/js/riot/riot-isomorphic/node_modules/riot/riot.js:735:12)
    at _tmpl (/home/lionel/dev/js/riot/riot-isomorphic/node_modules/riot/riot.js:707:43)
    at /home/lionel/dev/js/riot/riot-isomorphic/node_modules/riot/riot.js:1690:15
    at each (/home/lionel/dev/js/riot/riot-isomorphic/node_modules/riot/riot.js:1793:23)
    at update (/home/lionel/dev/js/riot/riot-isomorphic/node_modules/riot/riot.js:1686:3)
    at Tag.<anonymous> (/home/lionel/dev/js/riot/riot-isomorphic/node_modules/riot/riot.js:1452:5)
    at /home/lionel/dev/js/riot/riot-isomorphic/node_modules/riot/riot.js:130:12
    at String.replace (native)
    at RegExp.<anonymous> (/home/lionel/dev/js/riot/riot-isomorphic/node_modules/core-js/modules/$.fix-re-wks.js:20:48)
```

**Comment by lduboeuf** [comment]
node -v : `v5.1.1`
npm -v: `3.5.3`

**Comment by amitos80** [comment]
hi @lduboeuf, I get the same problem.
for now you can edit the package json to use "riot": "2.3.12" (and run npm install riot)
i'll fix the issue and will keep you posted.

**Comment by lduboeuf** [comment]
hi @amitos80 sorry, did't fix the problem with 2.3.12 and 2.3.15

**Comment by Avnerus** [comment]
Some angular style double curly braces somehow sneaked in there.
Should work now in most recent versions of Riot and Node.
Let me know if it works

**Comment by lduboeuf** [comment]
yes!, you did it ;-)
