### ISSUE TITLE
Error in routing table. Master branch.

### ISSUE THREAD

**Issue by zelid** [ListnPlay/riot-isomorphic#4]
[13:46:14] Using gulpfile ~/Workspace/page.js-demo1/riot-isomorphic/riot-isomorphic/gulpfile.js
[13:46:14] Starting 'html'...
[13:46:14] Finished 'html' after 25 ms
[13:46:14] Starting 'css'...
[13:46:14] Starting 'public-lib'...
[13:46:14] Starting 'js-client'...
[13:46:14] Starting 'js-server'...
[13:46:14] Starting 'js-app'...
[13:46:14] Starting 'env'...
[13:46:14] Finished 'env' after 94 μs
[13:46:15] Finished 'public-lib' after 298 ms
[13:46:15] Finished 'js-client' after 298 ms
[13:46:15] Finished 'css' after 334 ms
[13:46:15] Starting 'public-css'...
[13:46:15] Finished 'public-css' after 22 ms
[13:46:15] Finished 'js-server' after 320 ms
[13:46:15] Finished 'js-app' after 319 ms
[13:46:15] Starting 'browserify'...
[13:46:21] Finished 'browserify' after 6.47 s
[13:46:21] Starting 'public'...
[13:46:21] Finished 'public' after 21 ms
[13:46:21] Starting 'serve'...
livereload[tiny-lr] listening on 35729 ...
Routes class constructed!
Init FruitStore
Init ServerStore
running routingTable!
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Server.listen (net.js:1240:5)
    at EventEmitter.app.listen (/home/alex/Workspace/page.js-demo1/riot-isomorphic/riot-isomorphic/node_modules/express/lib/application.js:595:24)
    at EventEmitter.module.exports.listen (/home/alex/Workspace/page.js-demo1/riot-isomorphic/riot-isomorphic/node_modules/feathers/lib/application.js:107:30)
    at EventEmitter.self.(anonymous function) (/home/alex/Workspace/page.js-demo1/riot-isomorphic/riot-isomorphic/node_modules/feathers/node_modules/uberproto/lib/proto.js:61:21)
    at Object.<anonymous> (/home/alex/Workspace/page.js-demo1/riot-isomorphic/riot-isomorphic/build/server/index.js:98:6)
    at Module._compile (module.js:460:26)
    at normalLoader (/home/alex/Workspace/page.js-demo1/riot-isomorphic/riot-isomorphic/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:122:5)

**Comment by Avnerus** [comment]
Hi Alex,
The EADDRINUSE indicates there is another process listening on the port.
This also happened to me a few times, I believe it has something to do with crashes during gulp tasks.
Anyway running `killall node` shuold resolve this problem.
Let me know if it worked for you.
Thanks!

**Comment by zelid** [comment]
`killall node` helped, thank a lot!

**Comment by Avnerus** [comment]
np :)
