### ISSUE TITLE
error while gulp 

### ISSUE THREAD

**Issue by lichtner** [ListnPlay/riot-isomorphic#6]
```
marek@dell:~/www/riot/riot-isomorphic$ gulp
[13:37:59] Using gulpfile /home/www/riot/riot-isomorphic/gulpfile.js
[13:37:59] Starting 'html'...
[13:37:59] Finished 'html' after 4.18 ms
[13:37:59] Starting 'css'...
[13:37:59] Starting 'public-lib'...
[13:37:59] Starting 'js-client'...
[13:37:59] Starting 'js-server'...
[13:37:59] Starting 'js-app'...
[13:37:59] Starting 'env'...
[13:37:59] Finished 'env' after 37 μs
[13:37:59] Finished 'public-lib' after 30 ms
[13:37:59] Finished 'js-client' after 32 ms
[13:37:59] Finished 'css' after 79 ms
[13:37:59] Starting 'public-css'...
[13:37:59] Finished 'public-css' after 6.07 ms
[13:37:59] Finished 'js-server' after 81 ms
[13:37:59] Finished 'js-app' after 84 ms
[13:37:59] Starting 'browserify'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module './stores/server' from '/home/www/riot/riot-isomorphic/build/app'
    at /home/www/riot/riot-isomorphic/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/www/riot/riot-isomorphic/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/www/riot/riot-isomorphic/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/www/riot/riot-isomorphic/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by Avnerus** [comment]
Thanks for the catch.
Should be fixed now (https://github.com/ListnPlay/riot-isomorphic/commit/7606cb6f52b7350decc0efc2b3e685e6b32dd89e)

**Comment by lichtner** [comment]
thanks it works now
